openapi: 3.0.3
info:
  title: Todo API
  version: 1.0.0
  description: API for managing todo items
paths:
  /api-token-auth/:
    post:
      operationId: api_token_auth_create
      tags:
      - api-token-auth
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthToken'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AuthToken'
          application/json:
            schema:
              $ref: '#/components/schemas/AuthToken'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
          description: ''
  /api/todos/:
    get:
      operationId: api_todos_list
      description: Get list of todos for current user
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
          description: ''
    post:
      operationId: api_todos_create
      description: Create a new todo
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Todo'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Todo'
        required: true
      security:
      - tokenAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
          description: ''
  /api/todos/{id}/:
    get:
      operationId: api_todos_retrieve
      description: Get a specific todo by ID
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this todo
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
          description: ''
    put:
      operationId: api_todos_update
      description: Update a todo
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this todo
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Todo'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Todo'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
          description: ''
    patch:
      operationId: api_todos_partial_update
      description: Partially update a todo
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this todo
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedTodo'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedTodo'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedTodo'
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
          description: ''
    delete:
      operationId: api_todos_destroy
      description: Delete a todo
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this todo
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      responses:
        '204':
          description: No response body
components:
  schemas:
    AuthToken:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        token:
          type: string
          readOnly: true
      required:
      - password
      - token
      - username
    PatchedTodo:
      type: object
      description: Serializer for Todo model with complete CRUD operations
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          description: Title of the todo item
          maxLength: 200
        description:
          type: string
          nullable: true
          description: Detailed description of the todo item
        completed:
          type: boolean
          description: Whether the todo item is completed
        created_at:
          type: string
          format: date-time
          readOnly: true
          nullable: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        created_by:
          type: integer
          readOnly: true
          nullable: true
        updated_by:
          type: integer
          readOnly: true
          nullable: true
    Todo:
      type: object
      description: Serializer for Todo model with complete CRUD operations
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          description: Title of the todo item
          maxLength: 200
        description:
          type: string
          nullable: true
          description: Detailed description of the todo item
        completed:
          type: boolean
          description: Whether the todo item is completed
        created_at:
          type: string
          format: date-time
          readOnly: true
          nullable: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        created_by:
          type: integer
          readOnly: true
          nullable: true
        updated_by:
          type: integer
          readOnly: true
          nullable: true
      required:
      - created_at
      - created_by
      - id
      - title
      - updated_at
      - updated_by
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
